name: Eklenti Paketleyici ve Sürüm Oluşturucu

on:
  release:
    types: [published]

jobs:
  build_and_zip:
    name: ZIP Dosyası Oluştur ve Sürüme Ekle
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Eklenti Dosyalarını Arşivle
        run: zip -r guvenlik-tarayici.zip . -x ".git/*" ".github/*" "README.md" ".gitignore"

      # YUKARIDAKİ ADIMIN YERİNE BU GELDİ
      - name: ZIP Dosyasını Sürüme Yükle (gh CLI metodu)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload '${{ github.ref_name }}' ./guvenlik-tarayici.zip --clobber
